### PR TITLE
DB-703 simplify dashbase installation, use presto on dashbase chart

### PR DESCRIPTION
**Pull request by rluidash**
change on this PR

-- remove nopresto, nossl; by default dashbase will be secure by self-signed cert internally, and presto is included by default 

-- use presto from dashbase helm charts
-- change yaml, scripts storing location in adminpod's /database to persistent volume /data
-- expose grafana LB endpoints
-- updated default dashbase-values.yaml file for table resources and default resources.

### CODE REVIEW

**Comment by rluidash** [comment]
installer script has been tested on AWS platform

**Comment by khou** [comment]
> I haven't looked extensively at it, but how come we need to maintain two sets for smallsetup and normal setup? would advise against it and if we need a smaller deployment, setting different values for container requests/limits is probably better.

actually, if the user is requesting for a smaller set up after reading our requirements, we should pass in an entirely custom values yaml

**Comment by rluidash** [comment]
small setup script is for us to test installation in smaller environment and is not intended for customer to use

**Comment by rluidash** [comment]
the difference between regular and small setup, is on resource checking, and default dashbase-values.yaml file

**Pull request merged**
