### PR TITLE
Prepare asterisk config

### PR DESCRIPTION
**Pull request by sincejune**
Example log:
```
[Nov  4 07:46:30] VERBOSE[23765] asterisk.c: Asterisk Ready.
```

### CODE REVIEW

**Comment by sincejune** [comment]
that's because Asterisk and FreePBX will have different default format for datetime. Currently, the `freepbx.yml` only handles the the FreePBX default log formats.

**Comment by sincejune** [comment]
Also, updated the FreePBX parsers in this PR.
Fixed an issue that grok pattern can't have a subparser. Tested locally.

**Comment by sincejune** [comment]
These two files can not be merged into one single file using multi parsers like:
```
    _message_parser:
      type: multi
      parsers:
        freepbx:
          type: multi
          applyAll: "true"
          parsers:
            grok:
              type: grok
              pattern: "\\[%{TIMESTAMP_ISO8601:timestamp:datetime:yyyy-MM-dd HH:mm:ss}\\] %{WORD:level:meta}\\[%{INT:lwp:int}\\](\\[%{DATA:callid:text}\\])? %{JAVAFILE:source:meta}: %{GREEDYDATA:message}"
            sip:
              type: sip
        asterisk:
          type: multi
          applyAll: "true"
          parsers:
            grok:
              type: grok
              pattern: "\\[%{another}\\] %{WORD:level:meta}\\[%{INT:lwp:int}\\](\\[%{DATA:callid:text}\\])? %{JAVAFILE:source:meta}: %{GREEDYDATA:message}"
            sip:
              type: sip
```
Once one log entry have the SIP trace(can hit the sip parser), the first parser will always return true because `applyAll` only requires one parser hit.
What I wished to have is a parser like:
```
    _message_parser:
      type: multi
      parsers:
        freepbx:
          type: grok
            pattern: "\\[%{TIMESTAMP_ISO8601:timestamp:datetime:yyyy-MM-dd HH:mm:ss}\\] %{WORD:level:meta}\\[%{INT:lwp:int}\\](\\[%{DATA:callid:text}\\])? %{JAVAFILE:source:meta}: %{GREEDYDATA:message}"
            messageParser:
              type: sip
        asterisk:
          type: grok
          pattern: "\\[%{another}\\] %{WORD:level:meta}\\[%{INT:lwp:int}\\](\\[%{DATA:callid:text}\\])? %{JAVAFILE:source:meta}: %{GREEDYDATA:message}"
            messageParser:
              type: sip
```
Do we consider to add sub-parser support to grok parsers? @keitaf

**Comment by natalie-arsky** [comment]
I still don't understand.

We already have freepbx.yml
in dashbase-installation/dashbase/ansible/roles/filebeat/templates/configs


It defined separate pattern to parse log from asterisk and parse log from freepbx.
Why do we need to separate asterisk?

Here is what in freepbx.yml:


 paths:
    - /var/log/asterisk/full
  type: log
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: grok
      pattern: "\\[%{TIMESTAMP_ISO8601:timestamp:datetime:yyyy-MM-dd HH:mm:ss}\\] %{WORD:level:meta}\\[%{INT:lwp:int}\\] %{JAVAFILE:source:meta}: %{GREEDYDATA:message}"
      messageParser:
        type: sip

- paths:
    - /var/log/asterisk/freepbx.log
    - /var/log/asterisk/freepbx_security.log
  type: log
  close_inactive: 90s
  harvester_limit: 1000
  scan_frequency: 1s
  symlinks: true
  clean_removed: true
  fields:
    _message_parser:
      type: "timestamp"
      format: "yyyy-MMM-dd HH:mm:ss"
      scan: "true"

**Comment by sincejune** [comment]
After talking with @natalie-arsky personally, we decided to use a better merged parser and remove `asterisk.yml`.

Updated this PR and tested locally.

**Comment by sincejune** [comment]
@yangzb09 Could you apply this `freepbx.yml` into the demo cluster?

**Pull request merged**
